name: Deploy Sage 10 Theme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install PHP dependencies
        run: composer install

      - name: Install theme dependencies
        run: yarn add @roots/sage@6.21.0 @roots/bud@6.21.0 @roots/bud-tailwindcss@6.21.0 --dev swiper

      - name: Build theme
        run: yarn build

      - name: Start SSH agent and add key
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        shell: bash

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "cd /path/to/wordpress/wp-content/themes/palomo-theme && git pull && yarn add @roots/sage@6.21.0 @roots/bud@6.21.0 @roots/bud-tailwindcss@6.21.0 --dev swiper && yarn build"
